Task 84 general and structural backend refactoring
GroceryMateOst/GroceryMateCodeBase pull request #85
Opened 2023-04-11 07:12 UTC by mOceanracing

Die wichtigsten Anpassungen wurden unternommen:

- UserControler wurde thematisch in vers. Controller aufgeteilt
- Logik die unabhängig von injected-en-Objekten ist wurden in die Service-Klassen ausgelagert
- Integration-Tests wurden mittels In-Memory-Database aufgesetzt
- Validierungen wurden ebenfalls ausgelagert
- Fehlermeldungen werden nun spezifischer an das Frontend übergeben 
-

2023-04-11 08:11 UTC, tranfelix approved these changes

2023-04-11 12:40 UTC, glv12 requested changes

2023-04-13 06:42 UTC, mOceanracing commented on backend/grocery-mate-backend/WeatherForecast.cs
Chan mer scho use neh has eifach no guet gfunde au en möglichkeit ha z teste ob d api got wenn db us irgend emere grund ned tuet. Aber meinsch selli sie lieber au no mit use neh?

2023-04-13 06:43 UTC, mOceanracing commented on backend/grocery-mate-backend/Utility/GmLogger.cs
> +            return Symbols.Space + Symbols.SquareBracketsOpen + method + Symbols.SquareBracketsClose + Symbols.Space +
guete input wirdi no apass, thx

2023-04-13 06:51 UTC, glv12 commented on backend/grocery-mate-backend/WeatherForecast.cs
I hets jetzt usegnoh. Git ja au no ander möglichkeite zum teste ob backend funktioniert wen db nöd wür go.

2023-04-13 06:57 UTC, RamonEbneter commented on backend/grocery-mate-backend/WeatherForecast.cs
@glv12  @mOceanracing  meistens machtmer ufere API en health endpoint für das :) Vtl isch das jo no was zum ineneh
https://www.telerik.com/blogs/checking-health-aspnet-core-apis

2023-04-19 05:47 UTC, RamonEbneter approved these changes

2023-04-19 05:49 UTC, merged